# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (c) 2023, Mediatek Inc. All Rights Reserved.
# Author: Ren-Ting.Wang <ren-ting.wang@mediatek.com>

ccflags-y += -I$(src)/inc

obj-$(CONFIG_MTK_PCE) += pce.o

pce-y += cdrt.o
pce-y += cls.o
pce-y += dipfilter.o
pce-y += init.o
pce-y += netsys.o
pce-y += tport_map.o
pce-y += debugfs.o
